# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - /home/geoffroy/data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_ROOT_DATABASE: copabanana
  mongo-test:
    image: mongo
    restart: unless-stopped
    command: --port 27018
    ports:
      - 27018:27018
    tmpfs:
      - /tmp
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_ROOT_DATABASE: copabanana
          